<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>uk.gov.defra.tracesx</groupId>
  <artifactId>tracesx-springboot-common-azure</artifactId>
  <version>4.0.26</version>
  <name>azure</name>

  <parent>
    <groupId>uk.gov.defra.tracesx</groupId>
    <artifactId>tracesx-springboot-common</artifactId>
    <version>4.0.26</version>
  </parent>

  <scm>
    <connection>${parent.scm.connection}</connection>
    <tag>4.0.26-${env.BUILD_NUMBER}</tag>
  </scm>

  <dependencies>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
