trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  name: 'DEFRA-COMMON-UBUNTU-SSV5'

jobs:
  - job: Build
    displayName: Build
    condition: and(not(failed()), not(canceled()), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
      MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
    steps:
      - task: DownloadSecureFile@1
        name: mavenSettings
        displayName: 'Download Maven Settings'
        inputs:
          secureFile: 'maven-settings.xml'

      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo

      - task: Maven@4
        displayName: 'Build and Test'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx512m $(MAVEN_OPTS)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.21'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/*.xml'
          options: '--s $(mavenSettings.secureFilePath)'
          goals: 'clean test jacoco:report deploy --batch-mode'

      - task: PublishCodeCoverageResults@2
        displayName: 'Publish code coverage'
        inputs:
          summaryFileLocation: $(System.DefaultWorkingDirectory)/service/target/site/jacoco/jacoco.xml
          pathToSources: $(System.DefaultWorkingDirectory)/service/src/main/java/
